services:
  kpress-rabbitmq:
    image: rabbitmq:3.13
    container_name: kpress-rabbitmq
    ports:
      - "5552:5552"
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    command: >
      sh -c "
        rabbitmq-plugins enable rabbitmq_stream rabbitmq_stream_management &&
        rabbitmq-server
      "
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  kpress-db-gis:
    image: postgis/postgis:latest  
    container_name: kpress-db-gis
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "port=5432"]

  kpress-app-gis-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      kpress-db-gis:
        condition: service_healthy
      kpress-rabbitmq:
        condition: service_healthy
