FROM node:23-alpine3.20

# Install pnpm
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Accept build-time arguments
ARG PORT
ENV PORT=${PORT}

# Copy package.json and pnpm-lock.yaml
COPY package*.json pnpm-lock.yaml ./ 

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Remove .env file if it exists
RUN rm -f .env

# Replace .env with .env.prod
RUN cp .env.dev .env

# Expose the port on which the server will run
EXPOSE ${PORT}

# Start the backend server
CMD ["pnpm", "dev"]
